// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emnpliclwcfmvlwqxusr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbnBsaWNsd2NmbXZsd3F4dXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODA0MjQsImV4cCI6MjA2ODA1NjQyNH0.TvD2Ncbuhrzo2Nof3C5J4bn03EZHf2pHtAPcsgl33DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});